apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  annotations:
    github.com/project-slug: equinor/test-backstage
spec:
  type: other
  lifecycle: unknown
  owner: sw-enabling-team-developers
  
